# Generated by Django 5.2.3 on 2025-07-09 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Identificador da Estação')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Medição')),
                ('sensor', models.CharField(max_length=50, verbose_name='Tipo de Sensor')),
                ('medida', models.CharField(max_length=50, verbose_name='Medida')),
                ('valor', models.FloatField(verbose_name='Valor Medido')),
                ('unidade', models.CharField(max_length=20, verbose_name='Unidade')),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='est_sensores.estacao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
